### ISSUE TITLE
Binary doesn't run on OS X

### ISSUE THREAD

**Issue by gvol** [DamienCassou/textlint#12]
I don't expect you to package all possible binaries, but at least make a note that the binary is for linux only as well as instructions as to how to install a version that will run on other platforms.  It seems that I can actually get it to run by pointing `textlint-location-vm` to `PATH/TextLint.tmbundle/Support/TextLint.app/Contents/MacOS/Croquet`, but this took me quite a while to figure out.  If this could be detected automatically it would be great, but a note in the readme would suffice.

**Comment by DamienCassou** [comment]
Thanks for the feedback. Coud you please try the latest version? (commit b31e7bd2)

**Comment by gvol** [comment]
It works, though you might consider changing `textlint-guess-location-vm` to something like

```
(defun textlint-guess-location-vm ()
  (cond
   ((eq system-type 'darwin)
    'textlint-location-vm-macos)
   ((eq system-type 'windows-nt)
    'textlint-location-vm-windows)
   (t
    'textlint-location-vm-linux32)))
```

which is not perfect I'm sure, but might work for the majority of cases.  I haven't tested it on anything except my Mac which is all I have access to at the moment.

**Comment by DamienCassou** [comment]
Integrated in commit 617b9d3. Thank you very much. Next time, you can go to the page of the file in github (https://github.com/DamienCassou/textlint/blob/master/textlint.el) and click on the "Fork and edit this file" button. You get an editor embedded in the webbrowser and you can change from there.
