### ISSUE TITLE
BUG: Textlint couldn't parse the file path with spaces

### ISSUE THREAD

**Issue by liaison** [DamienCassou/textlint#16]
As described in the title,  Textlint could NOT work if the name of file or folder contains space. 

I haven't tested other cases, but may as well that it might not recognize other special characters in the name of file.

**Comment by DamienCassou** [comment]
This bug does not affect Emacs on Linux. As you are using Vim on MacOSX, I assign @cdlm to it.

Thanks for the feedback.

**Comment by cdlm** [comment]
Can you explain what's happening when? What's the relation with emacs or vim or the system??

**Comment by liaison** [comment]
I used Textlint with Vim. So I opened the file with Vim and run the command :TextLint. And then here is the error message: 
.....No such     file or directory
  Something bad happened!

The file name is like "research proposal.txt" with a space in between.  I found that Textlint only parsed the first word before space.
