### ISSUE TITLE
Textlint doesn't work with Mac OSX

### ISSUE THREAD

**Issue by liaison** [DamienCassou/textlint#17]
This might seem to be a silly question, seems like Textlint doesn't support Mac OSX. 

I found that there seem to be NO binary files for Mac OSX, after I went through all the installation and setup... 

Particularly, for the binary file "pharo", apparently it was compiled to be compatible with MacOSX. For the details below...  

/Users/..../.vim/bundle/textlint/Linux32/pharo: ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), for GNU/Linux 2.6.9, dynamically linked (uses shared libs), for GNU/Linux 2.6.9, not stripped

I would really like to see that works on my Mac.

**Comment by cdlm** [comment]
You looked in the wrong place, the Mac VM is inside the TextMate plugin :)
It does work here on Lion (though the Vim support is still WIP, as you have seen)

**Comment by DamienCassou** [comment]
Is there a problem of documentation with respect to this issue?

**Comment by cdlm** [comment]
I don't think so, unless you want users to run textlint from the image directly.
