### ISSUE TITLE
32bit ELF for linux

### ISSUE THREAD

**Issue by jpfairbanks** [DamienCassou/textlint#27]
I am having trouble getting textlint to work on 64 bit ubuntu 14.04 I have discovered the problem is that pharo is a 32bit elf.

```
>file ./textlint/Linux32/pharo
pharo: ELF 32-bit LSB  executable, Intel 80386, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.9, not stripped
```

Is there a reason that only 32bit is shipped? Can textlint be compiled for 64bit architectures?

**Comment by cdlm** [comment]
Pharo VMs compiled for 64bit architectures should be there in a few months. In the meantime, you will have to [install 32bit compatibility libs, as explained here](http://pharo.org/gnu-linux-installation)

**Comment by DamienCassou** [comment]
I would recommend installing Pharo from the Ubuntu PPA directly. Please pay attention, I don't maintain textline anymore.
