### ISSUE TITLE
Maintenance Plan

### ISSUE THREAD

**Issue by jpfairbanks** [DamienCassou/textlint#28]
Is there  a plan for anyone to take over this project? How many people are using it?
According to Github Network @chriscummins has forked the project and updated it on May 2015.

**Comment by ChrisCummins** [comment]
Hi James, Yes I forked it in order to make a couple of small changes (one is a useful improvement, the other is just a fix for my local system). I haven't been in contact with any of the authors however.

**Comment by jpfairbanks** [comment]
Since @DamienCassou is saying that he is no longer maintaining this repo, you might want to enable issues on your repo. 

Also are you using the vim plugin? I'm currently set up so that `:TextLint` runs the command and populates the quickfix list but `:cnext` does not move to the next lint error. I think it is because the errorformat does not match the format of the errors emitted.

**Comment by ChrisCummins** [comment]
While @DamienCassou may no longer be maintaining the repo, he is still active on GitHub. Let's give it a few days to see what he has to say. I'd be happy to assume a maintainer role, in which case it would make most sense to transfer repo ownership to me so we don't lose the open issues currently in the tracker.

**Comment by DamienCassou** [comment]
@ChrisCummins you now have write access to the repo. Thanks for taking over

**Comment by ChrisCummins** [comment]
Thanks @DamienCassou! @jpfairbanks, I'd suggest opening a new ticket for the issue with vim. I personally only use the emacs integration, but will happily review patches.
