### ISSUE TITLE
Paragraph ending

### ISSUE THREAD

**Issue by DamienCassou** [DamienCassou/textlint#3]
Currently, paragraph ending is defined in

```
TLWhiteSpace>>isEndOfParagraph
  token start to: token stop do: [ :index |
    (String crlf includes: (token collection at: index))
      ifTrue: [ ^ true ] ].
  ^ false
```

Which means each end of line is recognized as an end of paragraph. I propose that 2 end of lines identifies an end of paragraph, this is standard in a lot of format including LaTeX.

A fix could be to replace `^ true` by 

```
^ (token collection size = index)
   or: [String crlf includes: (token collection at: index + 1)]
```

What do you think?

**Comment by renggli** [comment]
On 6 September 2011 10:48, DamienCassou
reply@reply.github.com
wrote:

> Currently, paragraph ending is defined in
> 
>    TLWhiteSpace>>isEndOfParagraph
>      token start to: token stop do: [ :index |
>        (String crlf includes: (token collection at: index))
>          ifTrue: [ ^ true ] ].
>      ^ false
> 
> Which means each end of line is recognized as an end of paragraph. I propose that 2 end of lines identifies an end of paragraph, this is standard in a lot of format including LaTeX.

We always use dynamic word wrap.

Lukas

> A fix could be to replace `^ true` by
> 
>    ^ (token collection size = index)
>       or: [String crlf includes: (token collection at: index + 1)]
> 
> What do you think?
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/DamienCassou/textlint/issues/3

## 

Lukas Renggli
www.lukas-renggli.ch

**Comment by DamienCassou** [comment]
On Tue, Sep 6, 2011 at 11:08 PM, Lukas Renggli
reply@reply.github.com
wrote:

> We always use dynamic word wrap.

I don't understand

## 

Damien Cassou
http://damiencassou.seasidehosting.st

"Lambdas are relegated to relative obscurity until Java makes them
popular by not having them." James Iry

**Comment by DamienCassou** [comment]
Just to illustrate, the following expression

```
TLCaseRule new runOn: (TLTextLintChecker new parse: 'This is a case ', String cr, ' study') document.
```

returns a TLFailure, whereas

```
TLCaseRule new runOn: (TLTextLintChecker new parse: 'This is a case study') document.
```

doesn't

**Comment by renggli** [comment]
Yeah, I see the problem. I just hate if people put meaningless cr into
text files, that is from a time when editors couldn't do automatic
word wrapping and all screens were 80 characters wide.

Lukas

On 7 September 2011 10:48, Damien Cassou
reply@reply.github.com
wrote:

> Just to illustrate, the following expression
> 
>    TLCaseRule new runOn: (TLTextLintChecker new parse: 'This is a case ', String cr, ' study') document.
> 
> returns a TLFailure, whereas
> 
>    TLCaseRule new runOn: (TLTextLintChecker new parse: 'This is a case study') document.
> 
> doesn't
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/DamienCassou/textlint/issues/3#issuecomment-2026786

## 

Lukas Renggli
www.lukas-renggli.ch

**Comment by cdlm** [comment]
Even with soft wrapping, I often use explicit newlines to separate sentences inside paragraphs. Makes for clearer diff and easier merges.

**Comment by smarr** [comment]
@renggli I also prefer hard line breaks, just to get reasonable diff results if the diff viewers are not up to the task...

**Comment by renggli** [comment]
Fair enough, should be easy to add.

On 7 September 2011 15:04, Stefan Marr
reply@reply.github.com
wrote:

> @renggli I also prefer hard line breaks, just to get reasonable diff results if the diff viewers are not up to the task...
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/DamienCassou/textlint/issues/3#issuecomment-2028439

## 

Lukas Renggli
www.lukas-renggli.ch

**Comment by renggli** [comment]
Fixed in the latest code.
