### ISSUE TITLE
Add Jorge and Fabrizio

### ISSUE THREAD

**Issue by renggli** [DamienCassou/textlint#5]
Can you add Jorge and Fabrizio as members of the project? Since bug reports show up and they wrote most of the code I think this would be appropriate.

**Comment by DamienCassou** [comment]
On Thu, Sep 8, 2011 at 1:53 PM, Lukas Renggli
reply@reply.github.com
wrote:

> Can you add Jorge and Fabrizio as members of the project? Since bug reports show up and they wrote most of the code I think this would be appropriate.

I already added Jorge some times ago. What is Fabrizio's login?

## 

Damien Cassou
http://damiencassou.seasidehosting.st

"Lambdas are relegated to relative obscurity until Java makes them
popular by not having them." James Iry

**Comment by renggli** [comment]
Thanks. Don't know if Fabrizio has one.
