### ISSUE TITLE
Add support for emacs org-mode

### ISSUE THREAD

**Issue by DamienCassou** [DamienCassou/textlint#6]
I should first check if it is not already working by default

**Comment by DamienCassou** [comment]
It basically works without doing anything. A possible addition would be to use the initial starts '*\* ' as paragraph separators.

**Comment by renggli** [comment]
The tests are failing in my image. Please remove or fix.

**Comment by DamienCassou** [comment]
Very strange as they pass perfectly in my image. However, I have other failing tests, including TLTextParserTest>>testLatexMath

**Comment by DamienCassou** [comment]
Running `TLCachedParser flush` made all tests pass for me.
