### ISSUE TITLE
Support math mode in latex

### ISSUE THREAD

**Issue by DamienCassou** [DamienCassou/textlint#7]
The latex tokeniser should check ignore what is between dollars: e.g., $a + 3$

**Comment by renggli** [comment]
Name: TextLint-Model-lr.217
Author: lr
Time: 9 September 2011, 8:22:10 pm
UUID: 31b66b2c-4f79-4b76-bf14-82ef9200d137
Ancestors: TextLint-Model-DamienCassou.216
- consume mathematical expressions in latex
