### ISSUE TITLE
Find a better way to detect the tokenizer

### ISSUE THREAD

**Issue by DamienCassou** [DamienCassou/textlint#9]
Currently the tokenizer is chosen in both TLConsole>>check and TLTextLintChecker>>parse:.

It would be interesting to find a clean way to detect the tokenizer automatically.

**Comment by renggli** [comment]
Maybe better put TLOrgModeTokenizer in the console package, I don't see how that is useful in another context?

Name: TextLint-Model-lr.218
Author: lr
Time: 9 September 2011, 8:47:31 pm
UUID: e0da3f9d-8202-4690-8b88-0fa2a069b159
Ancestors: TextLint-Model-lr.217
- separate out which tokenizer to use
